---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local

  # Force Ansible to use your Conda Python by default; allow override via env ANSIBLE_PY
  vars:
    ansible_python_interpreter: "{{ lookup('env','ANSIBLE_PY') | default('/usr/bin/python3', true) }}"
  
  
    image_tag: latest
    dockerfile_path: "./"
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') | default('~/.kube/config', true) }}"

  # Make Docker SDK talk to the Unix socket (WSL)
  environment:
    DOCKER_HOST: "unix:///var/run/docker.sock"

  tasks:
    - name: Build Docker image
      community.docker.docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "nadhem9/{{ image_name }}:{{ image_tag }}"
        source: build
        state: present

    - name: Push Docker image
      community.docker.docker_image:
        name: "nadhem9/{{ image_name }}:{{ image_tag }}"
        push: true
        source: local

    - name: Ensure namespace exists
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: jenkins
        state: present
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Apply Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: deployment.yaml
        kubeconfig: "{{ kubeconfig_path }}"

    - name: Apply Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: "{{ kubeconfig_path }}"
