---
- name: Build and Deploy Docker Image to Kubernetes
  hosts: localhost
  connection: local
  gather_facts: false  # Disable fact gathering to avoid Python errors

  vars:
    image_name: my-country-service
    image_tag: latest
    dockerfile_path: './'
    docker_registry_username: "nadhem9"
    docker_registry_password: "nadhemaziz2003"
    ansible_python_interpreter: "/home/nadhem/miniconda3/bin/python"

  tasks:
    - name: Log in to Docker Hub
      community.general.docker_login:
        username: "{{ docker_registry_username }}"
        password: "{{ docker_registry_password }}"
        docker_host: unix:///var/run/docker.sock  # Ensure the Docker Host URL is set
        reauthorize: yes

    - name: Build Docker image
      docker_image:
        build:
          path: "{{ dockerfile_path }}"
        name: "{{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}"
        source: build
        state: present
        tag: "{{ image_tag }}"
        docker_host: unix:///var/run/docker.sock  # Ensure the Docker Host URL is set

    - name: Push the Docker image to Docker Hub
      docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}"
        tag: "{{ image_tag }}"
        push: yes
        source: local
        docker_host: unix:///var/run/docker.sock  # Ensure the Docker Host URL is set

    - name: Pull Docker image (optional, for verification or on target nodes)
      docker_image:
        name: "{{ docker_registry_username }}/{{ image_name }}:{{ image_tag }}"
        tag: "{{ image_tag }}"
        source: pull
        docker_host: unix:///var/run/docker.sock  # Ensure the Docker Host URL is set

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: deployment.yaml
        kubeconfig: config  # Adjust with the correct kubeconfig path

    - name: Apply Kubernetes Service
      kubernetes.core.k8s:
        state: present
        namespace: jenkins
        src: service.yaml
        kubeconfig: config  # Adjust with the correct kubeconfig path
